function joint_angle_Velocities = getJointAngularVelocities(dtf,dtp,dtt)
%getJointAngularVelocities
%    joint_angle_Velocities = getJointAngularVelocities(DTF,DTP,DTT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    09-Jun-2025 19:13:24

t2 = -dtf;
t3 = dtt+t2;
joint_angle_Velocities = [dtp+t2,t3,t3];
end
