function jointVelocities = getJointVelocities(dtf,dtp,dtt)
%getJointVelocities
%    jointVelocities = getJointVelocities(DTF,DTP,DTT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    15-May-2025 16:00:28

t2 = -dtf;
t3 = dtt+t2;
jointVelocities = [dtp+t2,t3,t3];
end
