function jointPositions = getJointPositions(lf,lm,lp,lt,tf,tm,tp,tt,xt,yt)
%getJointPositions
%    jointPositions = getJointPositions(LF,LM,LP,LT,TF,TM,TP,TT,XT,YT)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    09-Jun-2025 19:13:23

t2 = cos(tf);
t3 = cos(tm);
t4 = cos(tt);
t5 = sin(tf);
t6 = sin(tm);
t7 = sin(tt);
t8 = lf.*t2;
t9 = lm.*t3;
t10 = lt.*t4;
t11 = lf.*t5;
t12 = lm.*t6;
t13 = lt.*t7;
jointPositions = [xt;yt;t9+xt;t12+yt;t9+t10+xt;t12+t13+yt;t8+t9+t10+xt;t11+t12+t13+yt;t8+t9+t10+xt+lp.*cos(tp);t11+t12+t13+yt+lp.*sin(tp)];
end
