% This functions returns a CasADi function, which can be called when
% solving the NLP to compute the model constraint errors.

function f_getModelConstraintErrors = getModelConstraintErrors(...
    mp, mf, mt, mm, ...
    Ip, If, It, Im, ...
    lp, lf, lt, lm, ...
    lcf, lct, lcm, lc, ls, ...
    g, ks, lso, c)

    import casadi.*

    % CasADi variables.
    % Segment angles.
    % xp_MX = MX.sym('xp_MX',1);      yp_MX = MX.sym('yp_MX',1);      
    tp_MX = MX.sym('tp_MX',1);      tf_MX = MX.sym('tf_MX',1); 
    tt_MX = MX.sym('tt_MX',1);      tm_MX = MX.sym('tm_MX',1);
    % Segment angular velocities.
    % dxp_MX = MX.sym('dxp_MX',1);      dyp_MX = MX.sym('dyp_MX',1);      
    dtp_MX = MX.sym('dtp_MX',1);      dtf_MX = MX.sym('dtf_MX',1); 
    dtt_MX = MX.sym('dtt_MX',1);      dtm_MX = MX.sym('dtm_MX',1);
    % Segment angular accelerations.
    ddxt_MX = MX.sym('ddxt_MX',1);      ddyt_MX = MX.sym('ddyt_MX',1);      
    ddtp_MX = MX.sym('ddtp_MX',1);      ddtf_MX = MX.sym('ddtf_MX',1); 
    ddtt_MX = MX.sym('ddtt_MX',1);      ddtm_MX = MX.sym('ddtm_MX',1);
    % Joint torques.
    Th_MX = MX.sym('Th_MX',1);      Tk_MX = MX.sym('Tk_MX',1);     
    Ta_MX = MX.sym('Ta_MX',1);      Fx_MX = MX.sym('Fx_MX',1); 
    Fy_MX = MX.sym('Fy_MX',1);      Tt_MX = MX.sym('Tt_MX',1);
    
    % The equations of motion were described symbolically.
    constraintErrors = getSystemDynamics(...
        Fx_MX,Fy_MX,If,Im,Ip,It,Ta_MX,Th_MX,Tk_MX, Tt_MX, c, ...
        ddtf_MX,ddtm_MX,ddtp_MX,ddtt_MX,ddxt_MX,ddyt_MX,...
        dtf_MX,dtm_MX,dtp_MX,dtt_MX,g,ks,lc,...
        lcf,lcm,lct,lf,lm,lp,ls,lso, lt,mf,mm,mp,mt,...
        tf_MX,tm_MX,tp_MX,tt_MX);

    % CasADi function describing implicitly the model constraint errors.
    % f(q, dq, ddq, T) == 0.
    f_getModelConstraintErrors = Function(...
        'f_getModelConstraintErrors',{...
        tp_MX,tf_MX,tt_MX,tm_MX,...
        dtp_MX,dtf_MX,dtt_MX,dtm_MX,...
        ddxt_MX,ddyt_MX,ddtp_MX,ddtf_MX,ddtt_MX,ddtm_MX,...
        Th_MX,Tk_MX,Ta_MX,Tt_MX,Fx_MX,Fy_MX},{constraintErrors});
