function eq_vertical_toe_position = getVerticalToePos(lf,lm,lp,lt,tf,tm,tp,tt,yp)
%getVerticalToePos
%    EQ_VERTICAL_TOE_POSITION = getVerticalToePos(LF,LM,LP,LT,TF,TM,TP,TT,YP)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    12-May-2025 03:56:21

eq_vertical_toe_position = yp+lf.*sin(tf)+lm.*sin(tm)+lp.*sin(tp)+lt.*sin(tt);
end
